--sequences



--book_seq

CREATE SEQUENCE book_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999;

DROP SEQUENCE book_seq;


--category_seq

CREATE SEQUENCE category_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999;

DROP SEQUENCE category_seq;


--member_seq

CREATE SEQUENCE member_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999;

DROP SEQUENCE member_seq;

--orders_seq

CREATE SEQUENCE orders_seq START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999;

DROP SEQUENCE orders_seq;